#!/usr/bin/php
<?php

//this script needs to be in the root directory of your app to work properly.
//Make sure that you have run `composer install` if the autoloader isn't working.
include('vendor/autoload.php');

use Neptune\Tasks\TaskRunner;
use Neptune\Core\Config;

//load neptune cli config
$config = 'config/neptune.php';
if(file_exists($config)) {
	$c = Config::load('neptune', $config);
} else {
    echo 'creating';
	$c = Config::create('neptune', $config);
	$c->set('dir.root', __DIR__);
	$c->set('dir.neptune', __DIR__ . '/vendor/glynnforrest/neptune');
	$c->set('dir.skeletons', __DIR__ . '/vendor/glynnforrest/neptune/src/Neptune/Skeletons');
	$c->set('dir.app', __DIR__ . '/app');
	$c->save();
}

//prepare the command string
unset($_SERVER['argv'][0]);
$cmd = implode($_SERVER['argv'], ' ');

//off we go
TaskRunner::getInstance()->run($cmd);
